version: "3.7"

services:
    tsbs:
        container_name: tsbs
        build: .
        volumes:
            - .:/app
        working_dir: /app
        command: bash -c "npm install && node dist/server.js"
        ports:
            - ${PORT}:${PORT}
        networks:
            - frontend

networks:
    frontend:
        external:
            name: proxy
